{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.interval }}
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }}
{{- end }}