{
 "title": "Kuberentes Deprecation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "table",
   "description": "Cluster and manually create resources",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "deprecation_in_cluster{source=\"cluster\"}"
    }
   ]
  },
  {
   "title": "Helm V3",
   "type": "table",
   "description": "Helm V3 Resources.\nThe version may live in the `last-applied-configuration` annotation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "deprecation_in_cluster{source=\"helm3\"}"
    }
   ]
  },
  {
   "title": "Helm V2",
   "type": "table",
   "description": "Helm V2 and Tiller Resources.(hopefully none)\nThe version may live in the `last-applied-configuration` annotation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "deprecation_in_cluster{source=\"helm2\"}"
    }
   ]
  }
 ]
}